  [[main]]
  name = "ğŸ¡"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Articles ğŸ’¡"
  weight = 200
  identifier = "articles"
  url = "/articles/"


  [[main]]
  name = "Digital Garden ğŸŒ±"
  weight = 220
  identifier = "garden"
  url = "/garden/"

  [[main]]
  name = "Podcasts ğŸ™ï¸"
  weight = 300
  identifier = "podcasts"
  url = "/podcasts/"

  [[main]]
  name = "Talks ğŸ“£"
  weight = 400
  identifier = "talks"
  url = "/talks/"

  # [[footer]]
  # name = "imprint"
  # weight = 1
  # identifier = "imprint"
  # url = "/imprint/"