author = "Matthew Broberg"
title = "Matthew Broberg"
description = "Product & growth leader in cloud platform engineering, internal developer platforms, observability, and developer experience."
profilePicture = "images/profile.jpg"
keywords = "cloud platform engineering, internal developer platform, observability, incident management, developer experience, product management, growth, experimentation, team topologies, open source, digital garden"
favicon = "favicons/"
# example ["css/custom.css"]
# customCss = ["css/404.css"]
# example ["js/custom.js"]
#customJs = []
mainSections = ["articles"]
# Default image for social sharing (Open Graph and Twitter Cards)
images = ["images/mbbrobergfun.png"]
doNotLoadAnimation = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Fonts
googleFonts = ["Outfit"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "Jan 2, 2006"
indexDateFormat = "Jan 2, 2006"
listDateFormat = "Jan 2"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

[permalinks]
posts = '{{ replace .Name "-" " " | title }}'

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://floss.social/@mbbroberg"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/mbbroberg/"

[[socialIcons]]
icon = "fab fa-bluesky"
title = "Bluesky"
url = "https://bsky.app/profile/mbbroberg.fun"


[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/mbbroberg/"


[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:matthewbbroberg+io@gmail.com"

[[socialIcons]]
icon = "fas fa-rss"
title = "RSS"
url = "/index.xml"